"""create items table

Revision ID: a8dd6dcfea54
Revises: 58bd918995a9
Create Date: 2025-08-12 21:13:06.880753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8dd6dcfea54'
down_revision: Union[str, Sequence[str], None] = '58bd918995a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('nomination', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuididf', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type'], ['item_types.uuididf'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuididf')
    )
    op.create_index(op.f('ix_items_nomination'), 'items', ['nomination'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_nomination'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
