"""create warehouses table

Revision ID: b649356c9ed1
Revises: 81f3ea848e4e
Create Date: 2025-08-12 15:46:21.364928

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b649356c9ed1"
down_revision: Union[str, Sequence[str], None] = "81f3ea848e4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "warehouses",
        sa.Column("warehouse_name", sa.String(length=200), nullable=False),
        sa.Column("warehouse_worker_uuididf", sa.UUID(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuididf", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_worker_uuididf"],
            ["users.uuididf"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuididf"),
    )
    op.create_index(
        op.f("ix_warehouses_warehouse_name"),
        "warehouses",
        ["warehouse_name"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_warehouses_warehouse_name"), table_name="warehouses")
    op.drop_table("warehouses")
    # ### end Alembic commands ###
