"""create orders table

Revision ID: e11bef93c795
Revises: 98976c9a1214
Create Date: 2025-08-13 11:43:28.959520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e11bef93c795"
down_revision: Union[str, Sequence[str], None] = "98976c9a1214"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("status_uuididf", sa.UUID(), nullable=True),
        sa.Column("item_uuididf", sa.UUID(), nullable=True),
        sa.Column("warehouse_uuididf", sa.UUID(), nullable=True),
        sa.Column("customer_uuididf", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuididf", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_uuididf"],
            ["users.uuididf"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["item_uuididf"], ["items.uuididf"], onupdate="CASCADE", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["status_uuididf"],
            ["order_statuses.uuididf"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_uuididf"],
            ["warehouses.uuididf"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuididf"),
    )
    op.create_index(
        op.f("ix_orders_customer_uuididf"), "orders", ["customer_uuididf"], unique=False
    )
    op.create_index(
        op.f("ix_orders_item_uuididf"), "orders", ["item_uuididf"], unique=False
    )
    op.create_index(
        op.f("ix_orders_status_uuididf"), "orders", ["status_uuididf"], unique=False
    )
    op.create_index(
        op.f("ix_orders_warehouse_uuididf"),
        "orders",
        ["warehouse_uuididf"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_warehouse_uuididf"), table_name="orders")
    op.drop_index(op.f("ix_orders_status_uuididf"), table_name="orders")
    op.drop_index(op.f("ix_orders_item_uuididf"), table_name="orders")
    op.drop_index(op.f("ix_orders_customer_uuididf"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
