"""create characteristics items table

Revision ID: fe9da64a6dda
Revises: c29e83a6746e
Create Date: 2025-08-13 11:18:14.802397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9da64a6dda'
down_revision: Union[str, Sequence[str], None] = 'c29e83a6746e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characteristics_items',
    sa.Column('characteristic_uuiidf', sa.UUID(), nullable=False),
    sa.Column('item_uuiidf', sa.UUID(), nullable=False),
    sa.Column('int_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('string_value', sa.String(length=150), nullable=True),
    sa.Column('datetime_value', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuididf', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_uuiidf'], ['characteristics.uuididf'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_uuiidf'], ['items.uuididf'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuididf')
    )
    op.create_index(op.f('ix_characteristics_items_characteristic_uuiidf'), 'characteristics_items', ['characteristic_uuiidf'], unique=False)
    op.create_index(op.f('ix_characteristics_items_datetime_value'), 'characteristics_items', ['datetime_value'], unique=False)
    op.create_index(op.f('ix_characteristics_items_int_value'), 'characteristics_items', ['int_value'], unique=False)
    op.create_index(op.f('ix_characteristics_items_item_uuiidf'), 'characteristics_items', ['item_uuiidf'], unique=False)
    op.create_index(op.f('ix_characteristics_items_string_value'), 'characteristics_items', ['string_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characteristics_items_string_value'), table_name='characteristics_items')
    op.drop_index(op.f('ix_characteristics_items_item_uuiidf'), table_name='characteristics_items')
    op.drop_index(op.f('ix_characteristics_items_int_value'), table_name='characteristics_items')
    op.drop_index(op.f('ix_characteristics_items_datetime_value'), table_name='characteristics_items')
    op.drop_index(op.f('ix_characteristics_items_characteristic_uuiidf'), table_name='characteristics_items')
    op.drop_table('characteristics_items')
    # ### end Alembic commands ###
