name: WS_DOCKER
services:
  api-app:
    container_name: wsAPI
    build:
      context: .
      dockerfile: ws/Dockerfile
      target: dev
    volumes:
      - ./ws:/app/ws
    ports:
      - 8888:8000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT:?err}
      - TEST_POSTGRES_HOST=db-test
      - TEST_POSTGRES_PORT=${TEST_POSTGRES_PORT:?err}
    env_file:
      - .env
    command: ["python", "ws/main.py"]
    depends_on:
      db:
      db-test:
    networks:
      - ws-network
  db:
    image: postgres:18-alpine
    container_name: wsDB
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT:?err}:${POSTGRES_PORT:?err}
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
        reservations:
          cpus: "1"
          memory: 512M
    networks:
      - ws-network
  db-test:
    image: postgres:18-alpine
    container_name: wsTestDB
    ports:
      - ${TEST_POSTGRES_PORT:?err}:${TEST_POSTGRES_PORT:?err}
    environment:
      - POSTGRES_DB=${TEST_POSTGRES_DB:?err}
      - POSTGRES_USER=${TEST_POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD:?err}
      - POSTGRES_PORT=${TEST_POSTGRES_PORT:?err}
    command: -p ${TEST_POSTGRES_PORT:?err}
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
    networks:
      - ws-network
    
volumes:
  pgdata:
  pgdata-test:

networks:
  ws-network:
    driver: bridge